mqtt:
  host: test.mosquitto.org
  port: 1883
  #  port: 8884
  user: ""
  password: ""
  topic_prefix: mqtt_gpio
  protocol: 3.1.1
#  tls:
#    enabled: yes
#    ca_file: mosquitto.org.crt
#    certfile: client.crt
#    keyfile: client.key

gpio_modules:
  - name: stdio
    module: stdio

digital_inputs:
  - name: button
    module: stdio
    pin: 21
    on_payload: "ON"
    off_payload: "OFF"
    pullup: yes
    pulldown: no

digital_outputs:
  - name: bell
    module: stdio
    pin: 20
    on_payload: "ON"
    off_payload: "OFF"

logging:
  version: 1
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: INFO
  formatters:
    default:
      format: "%(asctime)s %(name)s [%(levelname)-8s] %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  loggers:
    mqtt_io:
      level: INFO
      handlers:
        - console
      propagate: yes
