mqtt:
  host: test.mosquitto.org
  port: 1883
  user: ""
  password: ""
  topic_prefix: pimqttgpio/mydevice

gpio_modules:
  - name: rpi
    module: raspberrypi

digital_inputs:
  - name: DoorBell_1
    module: rpi
    pin: 16
    on_payload: "true"
    off_payload: "false"

digital_outputs:
  - name: DoorOpen
    module: rpi
    pin: 17
    on_payload: "true"
    off_payload: "false
