mqtt:
  host: test.mosquitto.org
  # port: 1883
  port: 8883
  user: ""
  password: ""
  topic_prefix: mqtt_io
  clean_session: yes
  protocol: 3.1.1
  discovery: yes
  tls:
    enabled: yes
    ca_certs: mosquitto.org.crt
    # certfile: client.crt
    # keyfile: client.key

gpio_modules:
  - name: stdio
    module: stdio

digital_inputs:
  - name: test
    module: stdio
    pin: 22
    interrupt: rising

  - name: button
    module: stdio
    pin: 21
    on_payload: "ON"
    off_payload: "OFF"
    pullup: yes
    pulldown: no
    inverted: yes
    interrupt: rising
    interrupt_for:
      - test

digital_outputs:
  - name: bell
    module: stdio
    pin: 20
    on_payload: "ON"
    off_payload: "OFF"
    publish_initial: yes
    initial: high

logging:
  version: 1
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG
  formatters:
    default:
      format: "%(asctime)s %(name)s [%(levelname)-8s] %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  loggers:
    paho:
      level: DEBUG
      handlers:
        - console
      propagate: yes
    mqtt:
      level: DEBUG
      handlers:
        - console
      propagate: yes
    mqtt_io:
      level: DEBUG
      handlers:
        - console
      propagate: yes
