name: Run tests
on: push

jobs:
  test:
    name: Run tests with tox
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Run tox
        uses: docker://python:3.6
        run: tox -e py36
